#!/usr/bin/env bash

# This script displays a list of currently running processes for all users, including those without a TTY, in a user-oriented format with process hierarchy.

ps -e -o user,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,cmd --forest
