#!/usr/bin/env bash
# Create the PID file
echo $$ > /var/run/myscript.pid

# Function to handle SIGTERM signal
handle_sigterm() {
    echo "I hate the kill command"
}

# Function to handle SIGINT signal
handle_sigint() {
    echo "Y U no love me?!"
}

# Function to handle SIGQUIT signal
handle_sigquit() {
    rm /var/run/myscript.pid
    exit 0
}

# Trap signals and call respective functions
trap 'handle_sigterm' SIGTERM
trap 'handle_sigint' SIGINT
trap 'handle_sigquit' SIGQUIT

# Display message indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 1
done
