#!/usr/bin/env bash
# This init script manages the manage_my_process script

# Path to the manage_my_process script
SCRIPT="/path/to/manage_my_process"
# PID file
PIDFILE="/var/run/my_process.pid"

start() {
    echo "Starting manage_my_process..."
    $SCRIPT &
    echo $! > $PIDFILE
    echo "manage_my_process started"
}

stop() {
    if [ -f $PIDFILE ]; then
        PID=$(cat $PIDFILE)
        echo "Stopping manage_my_process..."
        kill $PID
        rm -f $PIDFILE
        echo "manage_my_process stopped"
    else
        echo "No manage_my_process PID file found"
    fi
}

restart() {
    echo "Restarting manage_my_process..."
    stop
    start
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
