#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process.
for pid in /proc/[0-9]*; do
  if [ -f "$pid/cmdline" ]; then
    if tr '\0' ' ' < "$pid/cmdline" | grep -q "4-to_infinity_and_beyond"; then
      kill "$pid"
    fi
  fi
done
