#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process.
for pid in /proc/[0-9]*; do
  if [ -f "$pid/cmdline" ]; then
    cmdline=$(cat "$pid/cmdline" | tr '\0' ' ')
    if [[ $cmdline == *4-to_infinity_and_beyond* ]]; then
      kill "$pid"
      echo "4-to_infinity_and_beyond process ($pid) has been terminated."
    fi
  fi
done