#!/usr/bin/env bash
# Get the process ID (PID) of the "7-highlander" process
PID=$(pgrep -f "7-highlander")
# If the process is running, send a termination signal
if [ -n "$PID" ]; then
    # Send SIGTERM signal to the process by writing to its /proc/<PID>/status file
    echo -n "T" > /proc/$PID/status
fi
